# Generated by Django 3.2.5 on 2021-07-25 16:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrepo', '0003_auto_20210725_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitions',
            name='partition_files',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/data/partitions'), upload_to=''),
        ),
    ]
